services:
  - type: web
    name: croldrop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
