const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const API='/api';let id=Number(tg?.initDataUnsafe?.user?.id)||Number(localStorage.uid)||Math.floor(Math.random()*900000000)+100000000;localStorage.uid=id;
let S={tab:'games',user:{stars:0},inventory:[],catalog:[],stake:null,target:null,chance:0,mode:null};const q=s=>document.querySelector(s);
async function api(p,o={}){let r=await fetch(API+p,{headers:{'Content-Type':'application/json'},...o});if(!r.ok)throw Error();return r.json()}
function toast(x){let e=q('#toast');e.textContent=x;e.style.display='block';setTimeout(()=>e.style.display='none',1800)}
function top(){return `<div class="top"><div class="brand">Crol<span>Drop</span></div><div class="balance">⭐ ${(S.user.stars||0).toLocaleString()}</div></div>`}
function card(n,click=''){return `<div class="card ${click?'click':''}" ${click?`onclick="${click}"`:''}><div class="icon">${n.symbol}</div><b>${n.name}</b><div class="rarity">${n.rarity}</div><div class="price">${n.price.toLocaleString()} ⭐</div></div>`}
function nav(){return `<div class="nav"><div class="navin">${[['games','◈','Игры'],['market','◇','Маркет'],['tasks','✦','Задания'],['profile','◉','Профиль']].map(x=>`<button class="${S.tab===x[0]?'active':''}" onclick="tab('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div></div>`}
function games(){return `<div class="hero"><div class="eyebrow">COLLECT · RISK · WIN</div><div class="title">CrolDrop</div><div class="muted">Собирай NFT и рискуй в системе Upgrade.</div></div><div class="section"><h2>Игры</h2><div class="grid">${card({symbol:'⬆',name:'UPGRADE',rarity:'РИСК И ВЫИГРЫШ',price:0},'openUpgrade()')}${card({symbol:'◈',name:'CASES',rarity:'СКОРО',price:0})}</div></div><div class="section"><h2>Твои NFT</h2><div class="grid">${S.inventory.map(card).join('')}</div></div>`}
function upgrade(){let a=S.stake,b=S.target;return `<div class="top"><button onclick="tab('games')" style="background:none;border:0;color:white;font-size:28px">‹</button><div class="brand">UP<span>GRADE</span></div><div></div></div><div class="ringbox"><div class="ring" style="--p:${S.chance}"><div class="ringin"><div class="eyebrow">ШАНС<div class="percent">${S.chance||'—'}%</div>УСПЕХА</div></div></div></div><div class="selection"><div class="pick ${a?'active':''}" onclick="pickStake()">${a?`<div class="icon">${a.symbol}</div><b>${a.name}</b><div class="price">${a.price} ⭐</div>`:'ВЫБРАТЬ NFT'}</div><div class="arrow">→</div><div class="pick ${b?'active':''}" onclick="pickTarget()">${b?`<div class="icon">${b.symbol}</div><b>${b.name}</b><div class="price">${b.price} ⭐</div>`:'ВЫБРАТЬ ЦЕЛЬ'}</div></div><div class="controls">${['x2','x4','x8','30%','50%','70%'].map(m=>`<button class="${S.mode===m?'active':''}" onclick="suggest('${m}')">${m}</button>`).join('')}</div><button class="mainbtn" onclick="upgradeNow()">⬆ ПРОКАЧАТЬ</button>`}
function market(){return `<div class="hero"><div class="eyebrow">MARKETPLACE</div><div class="title">NFT Market</div><div class="muted">Все предметы CrolDrop</div></div><div class="section"><div class="grid">${S.catalog.map(card).join('')}</div></div>`}
function tasks(){return `<div class="hero"><div class="eyebrow">REWARDS</div><div class="title">Задания</div><div class="muted">Забери стартовый бонус.</div></div><div class="section"><div class="card"><b>🎁 Стартовый бонус</b><div class="price">+1000 ⭐</div><button class="mainbtn" onclick="bonus()">ПОЛУЧИТЬ</button></div></div>`}
function profile(){return `<div class="hero"><div class="icon">◉</div><div class="title">${S.user.first_name||'Player'}</div><div class="muted">@${S.user.username||'player'}</div><div class="price">⭐ ${(S.user.stars||0).toLocaleString()}</div></div><div class="section"><h2>Инвентарь</h2><div class="grid">${S.inventory.map(card).join('')}</div></div>`}
function render(){let v=S.tab==='upgrade'?upgrade():S.tab==='games'?games():S.tab==='market'?market():S.tab==='tasks'?tasks():profile();q('#app').innerHTML=top()+v+(S.tab==='upgrade'?'':nav())}
function tab(x){S.tab=x;render()}function openUpgrade(){S.tab='upgrade';render()}
function modal(items,cb){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="sheet"><h2>Выбери NFT</h2>${items.map((n,i)=>`<div class="row" data-i="${i}"><div class="rowicon">${n.symbol}</div><div class="rowinfo"><b>${n.name}</b><div class="muted">${n.rarity}</div></div><b>${n.price} ⭐</b></div>`).join('')}</div>`;document.body.append(m);m.querySelectorAll('.row').forEach(e=>e.onclick=()=>{cb(items[+e.dataset.i]);m.remove()})}
function pickStake(){modal(S.inventory,n=>{S.stake=n;S.target=null;S.chance=0;S.mode=null;render()})}
function pickTarget(){if(!S.stake)return toast('Сначала выбери ставку');modal(S.catalog.filter(n=>n.price>S.stake.price),n=>{S.target=n;S.chance=Math.round(Math.max(1,Math.min(95,S.stake.price/n.price*96))*100)/100;S.mode=null;render()})}
async function suggest(mode){if(!S.stake)return toast('Выбери NFT');let d=await api(`/upgrade/suggest/${S.stake.inventory_id}/${mode}`);S.target=d.target;S.chance=d.chance;S.mode=mode;render()}
async function upgradeNow(){if(!S.stake||!S.target)return toast('Выбери ставку и цель');let d=await api('/upgrade',{method:'POST',body:JSON.stringify({telegram_id:id,stake_inventory_id:S.stake.inventory_id,target_nft_id:S.target.id})});let e=document.createElement('div');e.className='result';e.innerHTML=`<div class="resultbox"><div class="icon">${d.target.symbol}</div><h1 class="${d.won?'win':'lose'}">${d.won?'УСПЕШНО!':'НЕУДАЧА'}</h1><p>Шанс: ${d.chance}%</p><button class="mainbtn" onclick="this.closest('.result').remove();tab('games');load()">ПРОДОЛЖИТЬ</button></div>`;document.body.append(e)}
async function bonus(){let d=await api('/bonus',{method:'POST',body:JSON.stringify({telegram_id:id})});toast(d.message);load()}
async function load(){let u=tg?.initDataUnsafe?.user||{};let d=await api('/auth',{method:'POST',body:JSON.stringify({telegram_id:id,username:u.username||'',first_name:u.first_name||'Player'})});S.user=d.user;S.inventory=d.inventory;S.catalog=await api('/catalog');render()}load();
